@startuml
actor Visitor

Visitor -> UserInterface: Ask figures list page
activate UserInterface
UserInterface -> Domain: Execute use-case
activate Domain
Domain -> Infrastructure: Fetch figures list from database
Infrastructure -> Domain: Figures list
UserInterface -> Domain: Presents response
deactivate Domain
UserInterface -> Visitor: Render page with figures
@enduml
