security_controllers:
    resource: ../../src/UserInterface/Security/Controller/
    type: annotation

tricks_controllers:
    resource: ../../src/UserInterface/Trick/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
