@startuml
'https://plantuml.com/use-case-diagram
left to right direction

:Visitor:
:Member:

Member -|> Visitor

package Security {
    usecase "Login" as Login
    usecase "Register" as Register
    usecase "Logout" as Logout
    usecase "Ask new password" as AskNewPassword
    usecase "Change password" as ChangePassword
}

package Community {
    usecase "Add a trick to the trick's directory" as FigureCreate
    usecase "Edit a trick's from the directory" as FigureEdit
    usecase "Remove a trick's from the directory" as FigureDelete
    usecase "Post a message in the discussion space of a trick" as FigureMessageCreate
}

package Public {
    usecase "List snowboard tricks" as FiguresIndex
    usecase "See trick's details" as FiguresShow
    usecase "See trick's discussion messages" as FiguresReadMessages
}

Visitor --> FiguresIndex
Visitor --> FiguresShow
Visitor --> FiguresReadMessages
Visitor --> Login
Visitor --> Register

Member --> Logout
Member --> FigureCreate
Member --> FigureEdit
Member --> FigureDelete
Member --> FigureMessageCreate
Member --> AskNewPassword
Member --> ChangePassword

@enduml
